/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.io.BufferedWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import com.mycompany.OOP.UserManagement.EmployeeLogInFrame;
import com.mycompany.CP2.EmployeeVerification.Employees;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.time.LocalDateTime;


/**
 *
 * @author Yennie
 */
public class EmployeeMainFrame extends javax.swing.JDialog {
    private String authenticatedUsername; // This should be the only username variable in this class.
   
    public EmployeeMainFrame() throws IOException, FileNotFoundException, CsvValidationException {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Creates new form MainFrame
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws com.opencsv.exceptions.CsvValidationException
     */
    
    public EmployeeMainFrame(String username) {
        this.authenticatedUsername = username; // Initialize authenticatedUsername with the passed username.
        initComponents();
        setLocationRelativeTo(null);
        
   
   
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TimeOutBt = new javax.swing.JButton();
        TimeInBt = new javax.swing.JButton();
        LogOutEmp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimeOutBt.setBackground(new java.awt.Color(0, 0, 102));
        TimeOutBt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TimeOutBt.setForeground(new java.awt.Color(255, 255, 255));
        TimeOutBt.setText("Time Out");
        TimeOutBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeOutBtActionPerformed(evt);
            }
        });
        jPanel1.add(TimeOutBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 287, 110, 40));

        TimeInBt.setBackground(new java.awt.Color(0, 0, 102));
        TimeInBt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TimeInBt.setForeground(new java.awt.Color(255, 255, 255));
        TimeInBt.setText("Time In");
        TimeInBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeInBtActionPerformed(evt);
            }
        });
        jPanel1.add(TimeInBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 287, 100, 40));

        LogOutEmp.setBackground(new java.awt.Color(0, 0, 102));
        LogOutEmp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogOutEmp.setForeground(new java.awt.Color(255, 255, 255));
        LogOutEmp.setText("Log Out");
        LogOutEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutEmpActionPerformed(evt);
            }
        });
        jPanel1.add(LogOutEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Welcome!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yennie\\Downloads\\empframe.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -40, 650, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimeInBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeInBtActionPerformed
        // TODO add your handling code here:
        timeIn();
    }//GEN-LAST:event_TimeInBtActionPerformed

    private void TimeOutBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeOutBtActionPerformed
        // TODO add your handling code here:
        timeOut();
    }//GEN-LAST:event_TimeOutBtActionPerformed

    private void LogOutEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutEmpActionPerformed
        // TODO add your handling code here:
    EmployeeLogInFrame employeeLoginFrame = new EmployeeLogInFrame();
    employeeLoginFrame.setVisible(true);
    
    // Optionally, if you want to hide or dispose the current LoginFrame, you can call:
     this.dispose(); // to close the current frame
    }//GEN-LAST:event_LogOutEmpActionPerformed
    private void timeIn() {
        String formattedTime = LocalDateTime.now().toString();
        try {
            writeToCSV(authenticatedUsername, formattedTime, "IN"); // Use authenticatedUsername here
            JOptionPane.showMessageDialog(this, "Clocked in at: " + formattedTime);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing to CSV: " + e.getMessage());
        }
    }

    private void timeOut() {
        String formattedTime = LocalDateTime.now().toString();
        try {
            writeToCSV(authenticatedUsername, formattedTime, "OUT"); // Use authenticatedUsername here
            JOptionPane.showMessageDialog(this, "Clocked out at: " + formattedTime);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing to CSV: " + e.getMessage());
        }
}

// You'll need to implement the writeToCSV method if it doesn't exist already.
private void writeToCSV(String username, String formattedTime, String type) throws IOException {
    // The path to the CSV file
    Path csvFilePath = Paths.get("time_data.csv");

    // Using try-with-resources to ensure the writer is closed after use
    try (BufferedWriter writer = Files.newBufferedWriter(csvFilePath, StandardOpenOption.CREATE, StandardOpenOption.APPEND)) {
        // Create a new line with the user data
        String line = String.join(",", username, formattedTime, type);

        // Write the line to the CSV file
        writer.write(line);
        writer.newLine(); // This adds a new line after the record
    }
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EmployeeMainFrame().setVisible(true);
                } catch (IOException | CsvValidationException ex) {
                    Logger.getLogger(EmployeeMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutEmp;
    private javax.swing.JButton TimeInBt;
    private javax.swing.JButton TimeOutBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
